Edited and added comments. Started looking into adding functions
bjones1/StandardMechanics pull request #15
Opened 2023-04-21 02:46 UTC by Chaosking1623

2023-04-21 14:43 UTC, bjones1 requested changes
I'd like to see a bit more -- link to a line in the C# code (for example, the save image link) and explain what it does, in preparation for porting it.

2023-04-21 14:43 UTC, bjones1 commented on Image-acquisition-GUI/Python/grab_demo_testing.py
> +###################################################################################################
Make this (and similar text) render correctly in the CodeChat Editor. You can you Markdown now, so this might be:

```
# Create and Destroy Object
# -----------------------------
```

2023-04-26 03:39 UTC, Chaosking1623 commented on Image-acquisition-GUI/Python/grab_demo_testing.py
> +###################################################################################################
Updated some code and formatting.

2023-04-26 11:49 UTC, bjones1 approved these changes

2023-04-26 11:49 UTC, bjones1 commented on Image-acquisition-GUI/Python/grab_demo_testing.py
> +# <p>Create and Destroy Object -----------------------------</p>
For you next PR, make these a heading (probably a level 2 heading), so they stand out more in the CodeChat Editor.

2023-04-26 11:49 UTC, bjones1 commented on Image-acquisition-GUI/Python/grab_demo_testing.py
> +    m_Buffers.Load(m_FileDialog.FileName, 0)
Very exciting progress! However, a lot of this should be located in the GUI. Let's chat for the next PR.

2023-04-26 20:31 UTC, Chaosking1623 commented on Image-acquisition-GUI/Python/grab_demo_testing.py
> +    m_Buffers.Load(m_FileDialog.FileName, 0)
Thank you, we will work to implement some more C# into Python

2023-04-26 20:43 UTC, merged