Sprint Final PR
bjones1/StandardMechanics pull request #16
Opened 2023-04-26 21:29 UTC by KKonaOG

This SHOULD fully integrate most of the image acquisition requirements. It is completely untested. A slight remodel of the processing GUI was done to allow the image frame to be used in the cases of both image processing and image acquisition. A new .py was created to move previous team's work into a class that could be used more easily within the GUI, however, its contents should remain mostly the same. Some additional work was completed in an attempt to surplant the need to leverage the GrabDemo for its acquisition dialog. I was not entirely sure what the "Arm" button was going to be used for so I went ahead and wired up the trigger settings popup to that button. We also went ahead and created button for Serial Configuration. As you stated that we should mostly be focusing on Image Acquisition, I went ahead and remove JAISerial implementations and we simply left the buttons as a demonstration on how tab view can be used in the manner it was implemented.

2023-05-02 02:53 UTC, bjones1 commented
Would you add `pythonnet` and `pycairo` to `Image-processing-GUI/requirements.txt`? I need those to run the GUI.

...but, the `cairo` import is unused (likewise, `cv2` and `os` are also unused) -- can we just remove these instead?

2023-05-02 03:00 UTC, bjones1 requested changes

2023-05-02 03:00 UTC, bjones1 commented on Image-processing-GUI/New_GUI_LEAP.py
> +JAISerialHandle = None
Aack! Globals! Remove these, unless there's a **really** good reason for them...

2023-05-02 03:00 UTC, bjones1 commented on Image-processing-GUI/New_GUI_LEAP.py
> +        self.ImageAcquisitionHandle = ImageAcquisitionManager(self.ImageHandler)
This is what I'd expected instead of the global.

2023-05-02 03:00 UTC, bjones1 commented on Image-processing-GUI/New_GUI_LEAP.py
> +        if (ImageAcquisitionHandle is not None):
Aack! Global! Shouldn't this be `self.ImageAcquisitionHandle` instead? (See also the next line, line 134, etc.)

2023-05-03 23:23 UTC, KKonaOG commented
@bjones1 Ready for review

2023-05-04 14:41 UTC, bjones1 commented
Looks good, thanks!

2023-05-04 14:41 UTC, merged