Sprint 2 Final PR
bjones1/StandardMechanics pull request #17
Opened 2023-04-27 08:28 UTC by Chaosking1623

Added to grab_demo_testing.py and made very minor changes to other documents

2023-05-02 03:09 UTC, bjones1 commented
This PR makes no sense -- it's a merge of something earlier, but doesn't have new code in it. What's going on?

2023-05-02 04:59 UTC, Chaosking1623 commented
I am not sure, should I close this  and then submit a new one after doing a pull? The files changed I believe shows some changes we made to grab_demo_testing_.py.

2023-05-02 14:57 UTC, bjones1 commented
Never mind -- my mistake. Just address review comments.

2023-05-02 15:04 UTC, bjones1 requested changes

2023-05-02 15:04 UTC, bjones1 commented on Image-acquisition-GUI/Python/grab_demo_testing.py
> +            DestroyObjects()
This isn't defined until later in the code. (You call `CreateNewObjects` on line 230, but don't define `DestroyObjects` until line 258). Please fix.

2023-05-02 15:04 UTC, bjones1 commented on Image-acquisition-GUI/Python/grab_demo_testing.py
> +from asyncio.windows_events import NULL
Why is this imported? It's never used AFAIK.

2023-05-02 15:04 UTC, bjones1 commented on Image-acquisition-GUI/Python/grab_demo_testing.py
> +    if (not(CreateObjects())):
Should be `if not CreateObjects():`

2023-05-02 15:04 UTC, bjones1 commented on Image-acquisition-GUI/Python/grab_demo_testing.py
> +        DisposeObjects();
Don't end lines with a semicolon -- this is Python, not C.

2023-05-02 15:04 UTC, bjones1 commented on Image-acquisition-GUI/Python/grab_demo_testing.py
>      if (m_Acquisition != None and not m_Acquisition.Initialized):
Should be `if m_Acquisition is not None and not m_Acquisition.Initialized:`

See also line 212 and other similar items.

2023-05-02 15:04 UTC, bjones1 commented on Image-acquisition-GUI/Python/grab_demo_testing.py
>          if (m_Buffers.Create() == False):
Should be `if not m_Buffers.Create():`

2023-05-02 15:04 UTC, bjones1 commented on Image-acquisition-GUI/Python/grab_demo_testing.py
> +    if (m_Xfer != None):
`if m_Xfer is not None:`, similarly for following lines.

2023-05-02 15:04 UTC, bjones1 commented on Image-acquisition-GUI/Python/grab_demo_testing.py
> +if (m_isOpen):
`if m_isOpen:`

Also, this variable isn't declared yet...

2023-05-03 20:02 UTC, Chaosking1623 commented
Added the suggested changes to fit Python syntax.

2023-05-03 20:11 UTC, bjones1 commented
Better, but note that Python doesn't need `if (condition):`, instead use `if condition:` (no extra parenthesis).

I still see an error when I run this:

```
C:> python grab_demo_testing.py
Cancel
False
0
Traceback (most recent call last):
  File "C:\Users\bjones\Documents\git\StandardMechanics\Image-acquisition-GUI\Python\grab_demo_testing.py", line 250, in <module>
    CreateNewObjects(acConfigDlg, False)
  File "C:\Users\bjones\Documents\git\StandardMechanics\Image-acquisition-GUI\Python\grab_demo_testing.py", line 178, in CreateNewObjects
    if (not(CreateObjects())):
  File "C:\Users\bjones\Documents\git\StandardMechanics\Image-acquisition-GUI\Python\grab_demo_testing.py", line 206, in CreateObjects
    DestroyObjects()
NameError: name 'DestroyObjects' is not defined
```

2023-05-04 01:52 UTC, Chaosking1623 commented
I made some small changes, but I am not sure if it will fix DestroyObjects() not being defined. I thought it would be defined as it is before CreateNewObjects is called.

2023-05-04 14:33 UTC, bjones1 commented
It looks like you're making progress! However, I still get syntax errors when I run the program -- please fix these and ensure that it runs.

```
(venv_std_mechanics_310) C:\Users\bjones\Documents\git\StandardMechanics\Image-acquisition-GUI\Python>python grab_demo_testing.py
  File "C:\Users\bjones\Documents\git\StandardMechanics\Image-acquisition-GUI\Python\grab_demo_testing.py", line 295
    print("m_Buffers create success"):
                                     ^
SyntaxError: invalid syntax
```

2023-05-04 14:34 UTC, bjones1 commented on Image-acquisition-GUI/Python/grab_demo_testing.py
> +        if m_Xfer.Create() == False:
Use `if not m_Xfer.Create():` instead.

2023-05-04 14:34 UTC, bjones1 commented on Image-acquisition-GUI/Python/grab_demo_testing.py
> +    if m_Acquisition != None:
`if m_Acquisition is not None:`

2023-05-04 14:35 UTC, bjones1 requested changes
Still some syntax to update...

2023-05-05 19:12 UTC, Infernospike commented
Added the syntax changes that you requested

2023-05-08 20:55 UTC, bjones1 commented
Yes, just make the changes in this (main) branch then push -- that will update the PR with your changes. Make sure the code runs without raising an exception!

2023-05-08 22:15 UTC, bjones1 commented
Should I review now, or do you still have more to push?

2023-05-09 16:46 UTC, bjones1 commented
Never mind -- I tracked down the bug (assignment to a global variable without using the `global` keyword). Good enough, thanks!

2023-05-09 16:46 UTC, merged