Uploaded SDK pdf files and updated pre-writing hardware section.
bjones1/StandardMechanics pull request #2
Opened 2023-03-29 00:47 UTC by mpn21

Uploaded SDK pdf files and updated pre-writing hardware section.

2023-03-29 15:45 UTC, bjones1 requested changes
Is the TODO.txt file needed? Or can it be deleted?

2023-03-29 15:45 UTC, bjones1 commented on Serial-Communications/CameraCommunications.py
> +import serial
Add a link here -- I assume this is using PySerial? State that it needs to be pip installed. (Later, we need to create a package to make this installable...)

2023-03-29 15:45 UTC, bjones1 commented on Serial-Communications/CameraCommunications.py
> +# <p>Define Default Values</p>
Link to the JAI manual. A link of foo.pdf#page=3 for example opens the PDF to that page.

(You need to pull and build the latest version of the CodeChat Editor for this to work.)

This will probably be `COM1`.

2023-03-29 15:45 UTC, bjones1 commented on Serial-Communications/CameraCommunications.py
> +def GetSupportedBaudRates(serialHandle):
Again, link to the manual, which shows the command used to set the baud rate.

2023-03-29 15:45 UTC, bjones1 commented on Serial-Communications/CameraCommunications.py
> +    # <p>Parse the response</p>
Consider using a match/case statement. (Needs Python 3.10 or newer -- check to see what's installed.)

2023-03-29 15:45 UTC, bjones1 commented on Serial-Communications/CameraCommunications.py
> +def SetBaudRate(serialHandle, baudRate):
Document params nicely --

```
def SetBaudRate(
    # A handle to the serial port
    serialHandle,
    # The desired baud rate, in baud, as an int.
    baudRate,
):
```

2023-03-29 15:45 UTC, bjones1 commented on Serial-Communications/CameraCommunications.py
> +    elif response == b'01 Unknown Command!!\r\n':
Is the response really binary, not ASCII?

2023-03-29 15:45 UTC, bjones1 commented on Serial-Communications/requirements.txt
> +pyserial
I'll think about ways to document this in CodeChat.

2023-03-29 15:45 UTC, bjones1 commented on Serial-Communications/SimulatedCamera.py
> +import serial
What is this? I don't understand the purpose of this file.

2023-03-29 15:45 UTC, bjones1 commented on Serial-Communications/README.cchtml
> +<h1 style="text-align: center;"><span
I'll review this file separately.

2023-03-29 15:54 UTC, bjones1 commented on Serial-Communications/README.cchtml
> +<h1 style="text-align: center;"><span
My comments are here.

[README.zip](https://github.com/bjones1/StandardMechanics/files/11102805/README.zip)

2023-03-30 09:12 UTC, KKonaOG commented on Serial-Communications/CameraCommunications.py
> +    # <p>Parse the response</p>
I am using a fall through mechanism in order the array of supported baud rates, Sadly match in python automatically implements the case as if it were an "if", "else-if", ... "else" rather than dropping in at the first case it matches and falling through.

2023-03-30 09:13 UTC, KKonaOG commented on Serial-Communications/CameraCommunications.py
> +    elif response == b'01 Unknown Command!!\r\n':
This was an oversight on my end when implementing (brain fart) this was fixed in commit [fc29c3b](https://github.com/bjones1/StandardMechanics/pull/2/commits/fc29c3b61da2677b1213028e9bdc1c66a7d0780d)

2023-03-30 09:15 UTC, KKonaOG commented on Serial-Communications/SimulatedCamera.py
> +import serial
Without having a camera to test change baud rate I needed a file to simulate camera baud rate switching and proper communication after the switch. This file just pretends to be the camera using socap through linux to generate virtual com ports. Since it is outside the scope of work for this project, if will later be removed.

2023-03-30 09:17 UTC, KKonaOG commented on Serial-Communications/CameraCommunications.py
> +import serial
> Is the TODO.txt file needed? Or can it be deleted?

Removed during cleanup commit: [588f8d1](https://github.com/bjones1/StandardMechanics/pull/2/commits/588f8d1272ef9c34b6c06528d9874b8fb8e7f892)

2023-03-30 09:58 UTC, KKonaOG commented on Serial-Communications/README.cchtml
> +<h1 style="text-align: center;"><span
I BELIEVE all these changes were met by [f249eac](https://github.com/bjones1/StandardMechanics/pull/2/commits/f249eac4d02178325450d32fa3c12fde87de7c97)

There were significant changes between the two but I do believe we have them implemented

2023-03-30 10:14 UTC, KKonaOG commented on Serial-Communications/CameraCommunications.py
> +def SetBaudRate(serialHandle, baudRate):
Document using python standard in commit: [b7b2565](https://github.com/bjones1/StandardMechanics/pull/2/commits/b7b25657c046fcea2127855820c1d5f9124c930c)

2023-03-30 10:15 UTC, KKonaOG commented on Serial-Communications/CameraCommunications.py
> +# <p>Define Default Values</p>
I managed to get one link in working correctly in commit: [b7b2565](https://github.com/bjones1/StandardMechanics/pull/2/commits/b7b25657c046fcea2127855820c1d5f9124c930c)

Currently there is now a blocker due to a code chat bug I need to speak to you that is preventing CodeChat from "HTML"-izing the rest of the .py

2023-03-30 10:16 UTC, KKonaOG commented on Serial-Communications/CameraCommunications.py
> +def GetSupportedBaudRates(serialHandle):
I added in comments pointing to the data sheet until the blocker discussed here: https://github.com/bjones1/StandardMechanics/pull/2#discussion_r1152134049 is resolved

2023-04-04 22:14 UTC, bjones1 commented
Looks good -- would you manually resolve the conflicts, then post a message here? When I get that message, I'll merge.

2023-04-05 01:11 UTC, KKonaOG commented
Done @bjones1

2023-04-05 11:21 UTC, merged

2023-04-05 11:21 UTC, bjones1 commented
Thanks!